# name of the action
name: reviewdog

# trigger on pull_request events
on:
  pull_request:

# pipeline to execute
jobs:
  full-review:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_GITHUB_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yml -v"
          fail_on_error: true
          filter_mode: nofilter

