name: reviewdog
on:
  push:
    paths-ignore:
      - 'docs/**'
    branches: [ master ]

jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--no-config --issues-exit-code=1 --enable-all --disable=gomnd --disable=funlen --disable=goerr113 --disable=godot --disable=lll --disable=gocyclo --disable=gochecknoinits --disable=nakedret --disable=gochecknoglobals --tests=false --disable=goimports --disable=wsl --skip-dirs \"(^|/)templates($|/)\""
